name: Release to GitHub

on:
  push:
    tags:
      - 'v*' # 推送版本 tag 触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Build APK
        run: flutter build apk --release

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Upload AAB to GitHub Release
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec fastlane release_to_github

      - name: Upload APK to GitHub Release
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec fastlane release_to_github
